// ISO 3166-1 alpha-2 -> ISO 4217. Not exhaustive; extend as you travel.
export const countryToCurrency: Record<string, string> = {
  AT: 'EUR', BE: 'EUR', CY: 'EUR', DE: 'EUR', EE: 'EUR', ES: 'EUR',
  FI: 'EUR', FR: 'EUR', GR: 'EUR', HR: 'EUR', IE: 'EUR', IT: 'EUR',
  LT: 'EUR', LU: 'EUR', LV: 'EUR', MT: 'EUR', NL: 'EUR', PT: 'EUR',
  SI: 'EUR', SK: 'EUR',
  HU: 'HUF',
  PL: 'PLN',
  CZ: 'CZK',
  RO: 'RON',
  BG: 'BGN',
  RS: 'RSD',
  CH: 'CHF',
  LI: 'CHF',
  GB: 'GBP',
  NO: 'NOK',
  SE: 'SEK',
  DK: 'DKK',
  IS: 'ISK',
  TR: 'TRY',
  UA: 'UAH',
  US: 'USD',
  CA: 'CAD',
  MX: 'MXN',
};
